In [2]:
import pandas as pd

In [3]:
directory = "/Users/urshofmannelizondo/Documents/PhD/local_rag/test_data/"
df = pd.read_csv(f"{directory}metadata_V14.csv")

In [6]:
df_with_depth = df[df['depth'].isna()==False]
df_without_depth = df[(df['depth'].isna()==True)*(df['depth_original'].isna()==False)]
df_without_depth['depth'] = 'missing'

df_with_depth.to_csv(f'{directory}metadata_V14_with_depth.csv')
df_without_depth.to_csv(f'{directory}metadata_V14_without_depth.csv')

/var/folders/bv/kclw0qy52ksc563qxtd7lg480000gp/T/ipykernel_28236/3629375938.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_without_depth['depth'] = 'missing'

In [8]:
df_without_depth

,biosample,sample,...1,dataset,bioproject,sample_description,geo_loc_name,loc_description,lat,lon,...,reference,depth_layer,size fraction,size_fraction,marine_region,library_strategy,library_source,library_selection,read_count,base_count
4507,SAMEA7392424,KOPF15-1_SAMEA7392424,4309.0,KOPF15-1,"PRJEB8682,PRJEB40760,PRJEB40764",surface water sample from the Cretan Sea,not specified,not specified,35.550,24.310,...,NaN,NaN,NaN,NaN,Mediterranean Region,WGS,METAGENOMIC,RANDOM,149291856,22234944987
4514,SAMEA7392433,KOPF15-1_SAMEA7392433,4316.0,KOPF15-1,"PRJEB8682,PRJEB40760,PRJEB40764",surface water sample from the Mediterranean Sea,not specified,not specified,35.210,-2.850,...,NaN,NaN,NaN,NaN,Mediterranean Region,WGS,METAGENOMIC,RANDOM,175549546,26490582506
4528,SAMEA7392449,KOPF15-1_SAMEA7392449,4330.0,KOPF15-1,"PRJEB8682,PRJEB40760,PRJEB40764",surface water sample from the Atlantic Ocean,not specified,not specified,48.360,-4.550,...,NaN,NaN,NaN,NaN,North Atlantic Ocean,WGS,METAGENOMIC,RANDOM,177745634,26789311598
4575,SAMEA7422962,KOPF15-1_SAMEA7422962,4377.0,KOPF15-1,"PRJEB8682,PRJEB40760,PRJEB40764",surface water sample from the Cretan Sea,not specified,not specified,35.350,25.290,...,NaN,NaN,NaN,NaN,Mediterranean Region,WGS,METAGENOMIC,RANDOM,201755198,30424210177
4615,SAMEA7723412,SHAF22-1_SAMEA7723412,7788.0,SHAF22-1,PRJEB42019,Humpback whale feces (from individual AK1),not specified,not specified,56.900,-135.600,...,NaN,NaN,NaN,NaN,North Pacific Ocean,"c(""AMPLICON"", ""AMPLICON"", ""AMPLICON"", ""AMPLICO...","c(""METAGENOMIC"", ""METAGENOMIC"", ""METAGENOMIC"",...","c(""PCR"", ""PCR"", ""PCR"", ""PCR"", ""PCR"", ""PCR"", ""P...","c(36582, 16322, 20992, 2341, 30728, 2491, 6299...","c(2.72871319847135e-317, 1.21751361940544e-317..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11774,SAMN22234007,BRAM21-1_SAMN22234007,1853.0,BRAM21-1,PRJNA766133,Keywords: GSC:MIxS;MIMS:5.0,not specified,34.116 S 151.219 E,-34.116,151.219,...,NaN,NaN,NaN,NaN,South Pacific Ocean,WGS,GENOMIC,RANDOM,8805051,2448587866
11775,SAMN22234008,BRAM21-1_SAMN22234008,1854.0,BRAM21-1,PRJNA766133,Keywords: GSC:MIxS;MIMS:5.0,not specified,34.116 S 151.219 E,-34.116,151.219,...,NaN,NaN,NaN,NaN,South Pacific Ocean,WGS,GENOMIC,RANDOM,6091881,1662828175
11776,SAMN22234009,BRAM21-1_SAMN22234009,1855.0,BRAM21-1,PRJNA766133,Keywords: GSC:MIxS;MIMS:5.0,not specified,34.116 S 151.219 E,-34.116,151.219,...,NaN,NaN,NaN,NaN,South Pacific Ocean,WGS,GENOMIC,RANDOM,551230,161987053
11777,SAMN22234010,BRAM21-1_SAMN22234010,1856.0,BRAM21-1,PRJNA766133,Keywords: GSC:MIxS;MIMS:5.0,not specified,34.116 S 151.219 E,-34.116,151.219,...,NaN,NaN,NaN,NaN,South Pacific Ocean,WGS,GENOMIC,RANDOM,1273585,377270848
11778,SAMN22234011,BRAM21-1_SAMN22234011,1857.0,BRAM21-1,PRJNA766133,Keywords: GSC:MIxS;MIMS:5.0,not specified,34.116 S 151.219 E,-34.116,151.219,...,NaN,NaN,NaN,NaN,South Pacific Ocean,WGS,GENOMIC,RANDOM,6363950,1883501153